language: node_js
node_js:
  - "8"
  - "node"
cache:
  directories:
    - "node_modules"
sudo: required
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - firefox
install:
  - npm install
script:
  - npm run lint
  - npm run test:cover
after_success:
  - npm run coveralls
